server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: csv_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: csv_logs
          __path__: /tmp/logs/*.log
    pipeline_stages:
      - regex:
          expression: '^(?P<timestamp>\S+) \[(?P<level>\S+)\] (?P<service>[^:]+): (?P<message>.*)'