version: '3.7'

services:
  influxdb:
    image: influxdb:2
    container_name: influxdb
    networks:
      - main_network
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
      - ./influxdb/config:/etc/influxdb2
    environment:
      - INFLUXDB_DB=maindb
      - INFLUXDB_ADMIN_USER=put101
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    networks:
      - main_network
    ports:
      - "3000:3000"
    volumes:
      - grafana_storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}

networks:
  main_network:

volumes:
  influxdb_data:
  grafana_storage:

